import type { ProducerRequest, ProducerResult } from "./schema";
import { titleize } from "@/lib/utils";

// Deterministic fallback producer used when no ANTHROPIC_API_KEY is set. Ranks
// candidates by their existing order and synthesizes plausible copy so the whole
// pipeline runs without the real model. Same output shape as the Claude path.
export function mockProduce(req: ProducerRequest): ProducerResult {
  const chosen = req.candidates.slice(0, req.maxSelections);
  const selections = chosen.map((c, i) => {
    const rank = i + 1;
    return {
      candidateClipId: c.candidateClipId,
      rank,
      category: c.category,
      selectionReason: `Strong ${titleize(c.category).toLowerCase()} moment from ${c.sourceName}; clear payoff in the transcript.`,
      suggestedTitle: c.videoTitle.toUpperCase().slice(0, 60),
      suggestedCaption: `You have to see this one 👀 #${rank} of the day.`,
      suggestedDescription: c.videoTitle,
      suggestedHashtags: ["#ballknower", "#sports", "#top7", `#${c.category.toLowerCase()}`],
      suggestedOnScreenText: `#${rank}`,
      suggestedLowerThird: `${c.sourceName} • ${titleize(c.category)}`,
      suggestedVoiceover: `Number ${rank}.`,
      suggestedTransition: "Hard cut on the action.",
      suggestedFilmingPrompt: `React to clip #${rank}.`,
      reviewFlags: c.category === "BREAKING_NEWS" ? ["Verify before posting — breaking news."] : [],
      needsReview: c.category === "BREAKING_NEWS",
    };
  });

  const filmingPrompts = [
    { slot: "hook", order: 0, prompt: "Film a 3-second hook teasing the #1 clip." },
    ...selections
      .slice()
      .reverse()
      .map((s, i) => ({
        slot: `reaction_rank_${s.rank}`,
        order: i + 1,
        prompt: `React to clip ranked #${s.rank}.`,
      })),
    { slot: "outro", order: selections.length + 1, prompt: "Film your outro + CTA: follow for daily." },
  ];

  return {
    summary: `${titleize(req.format)} with ${selections.length} clips (generated by the fallback producer).`,
    selections,
    filmingPrompts,
  };
}
